//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Libary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangDay
    {
        public int id { get; set; }
        public string MaMon { get; set; }
        public string MaGV { get; set; }
        public string MaLop { get; set; }
        public string NienKhoa { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
