//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Libary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int Id { get; set; }
        public string Lop { get; set; }
        public string ChuDe { get; set; }
        public Nullable<int> BaiGiang { get; set; }
    
        public virtual BaiGiangs_TaiNguyens BaiGiangs_TaiNguyens { get; set; }
    }
}
