//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Libary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int Id { get; set; }
        public string TenVaiTro { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MonHoc { get; set; }
        public Nullable<int> TepRiengTu { get; set; }
        public Nullable<int> TaiNguyen { get; set; }
        public Nullable<int> De { get; set; }
        public Nullable<int> ThongBao { get; set; }
        public Nullable<int> PhanQuyen { get; set; }
        public string NguoiDung { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
