//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Libary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public int Id { get; set; }
        public Nullable<int> Ma { get; set; }
        public string NguoiPheDuyet { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string TinhTrang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BaiGiangs_TaiNguyens BaiGiangs_TaiNguyens { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
